- name: Testing fileinline
  hosts: testservers
  become: yes
  gather_facts: true
  vars:
    os1family: "Debian"
    os2family: "RedHat"
  tasks:
    - name: Copy sshd_config file
      copy:
        src: sshd_config
        dest: /etc/ssh/sshd_config
        force: yes
      when: ansible_os_family == "{{ os1family }}"
      notify:
        - Restart SSH Service

    - name: Replace line 'PasswordAuthentication no' with 'PasswordAuthentication yes'
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication no"
        line: "PasswordAuthentication yes"
        backup: yes
      notify:
        - Restart SSH Service

  handlers:
    - name: Restart SSH Service
      service:
        name: sshd
        state: restarted
