- name: Testing fileinline
  hosts: testserver
  become: yes
  gather_facts: true
  vars:
    os1family: "Debian"
    os2family: "RedHat"
    mypassword: india@1234
  tasks:
    - name: Copy sshd_config file
      copy:
        src: sshd_config
        dest: /etc/ssh/sshd_config
        force: yes
      when: ansible_os_family == "{{ os1family }}"
      notify:
        - Restart SSH Service

    - name: Replace line 'PasswordAuthentication no' with 'PasswordAuthentication yes'
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication no"
        line: "PasswordAuthentication yes"
        backup: yes
      notify:
        - Restart SSH Service
    - name: change user password
      ansible.builtin.user:
        name: ubuntu
        state: present
        password: "{{ mypassword | password_hash('sha512') }}"
    - name: Replace line 'Pubkey yes' with 'Pubkey no'
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#PubkeyAuthentication yes"
        line: "PubkeyAuthentication no"
        backup: yes
      notify:
        - Restart SSH Service

  handlers:
    - name: Restart SSH Service
      service:
        name: sshd
        state: restarted
